spring:
  datasource:
    url: jdbc:h2:mem:payments-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  profiles:
    active: sandbox

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

mercadopago:
  access-token: ${MERCADO_PAGO_ACCESS_TOKEN}